baseURL = ""
publishDir = "public_pdf"

[params]
  isPDF = true
  theme_css = [
    "/css/vivlio-theme-manual.css",
    "/css/vivlio-theme-manual-bookoption.css" # add book style (consider left/right page)
    ]
  showIfs = ["test"]
  sectionNumberLevel = 3
  # sectionDelimiter = "-"
  # sectionTopFormat = "Chapter %s"

[languages]
  [languages.jp.params]
    sectionTopFormat = "第%s章"